# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.DEVELOPER_DOCS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Push File
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'api-integration.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: 'docs/bcc-membership-docs'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Update Membership Docs'

      - name: Push File
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'data-structures-and-scopes.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: 'docs/bcc-membership-docs'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Update Membership Docs'
          
      - name: Push File
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'index.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: 'docs/bcc-membership-docs'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Update Membership Docs'

      - name: Push File
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'single-sign-out.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: 'docs/bcc-membership-docs'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Update Membership Docs'
      
      - name: Push File
        uses: dmnemec/copy_file_to_another_repo_action@main
        with:
          source_file: 'webhooks.md'
          destination_branch: 'master'
          destination_repo: 'bcc-code/bcc-code.github.io'
          destination_folder: 'docs/bcc-membership-docs'
          user_email: 'nicolai.velzel@gmail.com'
          user_name: 'nvelinz'
          commit_message: 'Update Membership Docs'